//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Admin.Models.Model
{
    using System;
    public class Admins : BaseModel<string>
    {
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string PassSalt { get; set; }
        public string RoleId { get; set; }
        public DateTime? LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
        public string LastLoginToken { get; set; }
        public string Remark { get; set; }
    }
}
