//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Admin.Models.Model
{
    public class Menus : BaseModel<string>
    {
        public string ParentId { get; set; }
        public string Name { get; set; }
        /// <summary>
        /// 链接
        /// </summary>
        public string Router { get; set; }
        public string RouterName { get; set; }
        public string Icon { get; set; }
        public EMenuType MenuType { get; set; }
        public string RoutePath { get; set; }
    }
}
